### ISSUE TITLE
not working properly

### ISSUE THREAD

**Issue by scmaxsr** [pwt/docker-sonos-web-arm#1]
hi 
i have installed the docker image al go well and i get to the website but things work properly
music library 
my sonos
and spotify
it's sluggy and later on i get 401 error

what doing wrong

sorry for mij bad english
keep up te good work

**Comment by pwt** [comment]
Unfortunately, I'm not sure I can help much with this because I don't know anything about the internals of sonos-web; I just provide the Docker build and packaging.

However, I've changed the base Node image from which the container is built. This has some updates and may improve reliability/performance. Give it a try. 

You may also want to raise your issue as part of the main project: https://github.com/Villarrealized/sonos-web

**Comment by scmaxsr** [comment]
ok thanks
